import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import React from "react";

import "@shared/styles/globals.scss";
import LocaleProvider from "@shared/providers/LocaleProvider";
import AntdProvider from "@shared/providers/AntdProvider";
import { createClient } from "@shared/config/superbase/server";
import UserProvider from "@shared/providers/UserProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ubuntu = Ubuntu({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang="en">
      <body className={ubuntu.className}>
        <LocaleProvider>
          <AntdProvider>
            <UserProvider user={user}>
              {children}
            </UserProvider>
          </AntdProvider>
        </LocaleProvider>
      </body>
    </html>
  );
}
